const vanData = [
    {
        vanCategory: "Ambition Lite",
        capacity: {
            "Extra Small": 15,
            Small: 10,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },
    {
        vanCategory: "Ambition Central",
        capacity: {
            "Extra Small": 40,
            Small: 30,
            Medium: 10,
            "Medium +": 5,
            Large: 5,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.3,
            Medium: 0.675,
            "Medium +": 0.745,
            Large: 0.9,
            "Extra Large": 0.97,
        },
    },
    {
        vanCategory: "Ambition Central-Hi",
        capacity: {
            "Extra Small": 45,
            Small: 40,
            Medium: 10,
            "Medium +": 5,
            Large: 5,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.3,
            Medium: 0.675,
            "Medium +": 0.745,
            Large: 0.9,
            "Extra Large": 0.97,
        },
    },
    {
        vanCategory: "Ambition Large",
        capacity: {
            "Extra Small": 50,
            Small: 40,
            Medium: 15,
            "Medium +": 10,
            Large: 10,
            "Extra Large": 5,
        },
        pricing: {
            "Extra Small": 0.105,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },
    {
        vanCategory: "Ambition Extra Large",
        capacity: {
            "Extra Small": 60,
            Small: 35,
            Medium: 15,
            "Medium +": 15,
            Large: 10,
            "Extra Large": 5,
        },
        pricing: {
            "Extra Small": 0.125,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },
    {
        vanCategory: "Ambition Crew",
        capacity: {
            "Extra Small": 40,
            Small: 30,
            Medium: 10,
            "Medium +": 5,
            Large: 5,
            "Extra Large": 5,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.3,
            Medium: 0.675,
            "Medium +": 0.745,
            Large: 0.9,
            "Extra Large": 0.97,
        },
    },
    {
        vanCategory: "Ambition Group",
        capacity: {
            "Extra Small": 55,
            Small: 40,
            Medium: 15,
            "Medium +": 10,
            Large: 5,
            "Extra Large": 5,
        },
        pricing: {
            "Extra Small": 0.105,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },
    {
        vanCategory: "Ambition Assist",
        capacity: {
            "Extra Small": 10,
            Small: 20,
            Medium: 5,
            "Medium +": 3,
            Large: 5,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },

    {
        vanCategory: "Ambition Environment Lite",
        capacity: {
            "Extra Small": 15,
            Small: 10,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },

    {
        vanCategory: "Ambition Environment Central",
        capacity: {
            "Extra Small": 40,
            Small: 30,
            Medium: 10,
            "Medium +": 5,
            Large: 5,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.3,
            Medium: 0.675,
            "Medium +": 0.745,
            Large: 0.9,
            "Extra Large": 0.97,
        },
    },


    {
        vanCategory: "Ambition Environment Large",
        capacity: {
            "Extra Small": 50,
            Small: 40,
            Medium: 15,
            "Medium +": 10,
            Large: 10,
            "Extra Large": 5,
        },
        pricing: {
            "Extra Small": 0.105,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },

    {
        vanCategory: "Ambitious",
        capacity: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
    },

    {
        vanCategory: "Ambitious XL",
        capacity: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
    },

    {
        vanCategory: "Ambitious Luxury",
        capacity: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
    },

    {
        vanCategory: "Ambitious Executive",
        capacity: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
    },

    {
        vanCategory: "Ambitious Environment",
        capacity: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
    },

    {
        vanCategory: "Ambitious Assist",
        capacity: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
    },

    {
        vanCategory: "Ambitious Team",
        capacity: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
    },

    {
        vanCategory: "Ambition Pet",
        capacity: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0,
            Small: 0,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
    },

    {
        vanCategory: "Ambition Small Luton",
        capacity: {
            "Extra Small": 70,
            Small: 65,
            Medium: 25,
            "Medium +": 15,
            Large: 15,
            "Extra Large": 5,
        },
        pricing: {
            "Extra Small": 0.175,
            Small: 0.7,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.325,
            "Extra Large": 1.425,
        },
    },
    {
        vanCategory: "Ambition Big Luton",
        capacity: {
            "Extra Small": 75,
            Small: 70,
            Medium: 30,
            "Medium +": 10,
            Large: 20,
            "Extra Large": 10,
        },
        pricing: {
            "Extra Small": 0.2,
            Small: 0.7,
            Medium: 0.925,
            "Medium +": 1.045,
            Large: 1.375,
            "Extra Large": 1.475,
        },
    },

    {
        vanCategory: "Ambition Refrigeration Lite",
        capacity: {
            "Extra Small": 15,
            Small: 10,
            Medium: 0,
            "Medium +": 0,
            Large: 0,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },

    {
        vanCategory: "Ambition Refrigeration Central",
        capacity: {
            "Extra Small": 40,
            Small: 30,
            Medium: 10,
            "Medium +": 5,
            Large: 5,
            "Extra Large": 0,
        },
        pricing: {
            "Extra Small": 0.055,
            Small: 0.3,
            Medium: 0.675,
            "Medium +": 0.745,
            Large: 0.9,
            "Extra Large": 0.97,
        },
    },

    {
        vanCategory: "Ambition Refrigeration Large",
        capacity: {
            "Extra Small": 50,
            Small: 40,
            Medium: 15,
            "Medium +": 10,
            Large: 10,
            "Extra Large": 5,
        },
        pricing: {
            "Extra Small": 0.105,
            Small: 0.575,
            Medium: 0.875,
            "Medium +": 0.945,
            Large: 1.275,
            "Extra Large": 1.345,
        },
    },
];
